id = "lume"
name = "lume"
description = "lume"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lume_zed"

[grammars.lume]
repository = "https://github.com/orlaya/lume_tree"
commit = "413d87d979d2fa198cbe116ec73253eb50c0081c"
