id = "lume"
name = "lume"
description = "lume"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lume_zed"

[grammars.lume]
repository = "https://github.com/orlaya/lume_tree"
commit = "2e87a067ace8f0d290a8bb6a3165e5eefbf104ff"
