id = "lume"
name = "lume"
description = "lume"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lume_zed"

[grammars.lume]
repository = "https://github.com/orlaya/lume_tree"
commit = "c24be50e9367d7e92bb6d36b1cd96a3e66556f7f"
